version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/alphas"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/betas"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/rcs"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/stables"
    schedule:
      interval: "daily"