[versions]
androidx-compose-compiler = "1.5.3"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.9.10" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.9.10" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version = "1.9.10" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version = "1.9.10" }

kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "1.9.10" }

android-application = { id = "com.android.application", version = "8.1.0" }
android-library = { id = "com.android.library", version = "8.1.0" }

ksp = { id = "com.google.devtools.ksp", version = "1.9.10-1.0.13" }
skie = { id = "co.touchlab.skie", version = "0.4.19" }
jib = { id = "com.google.cloud.tools.jib", version = "3.4.0" }

gradle-plugin-publish = { id = "com.gradle.plugin-publish", version = "1.2.1" }
qoomon-git-versioning = { id = "me.qoomon.git-versioning", version = "6.4.2" }
gradle-nexus-publish-plugin = { id = "io.github.gradle-nexus.publish-plugin", version = "1.1.0" }

[libraries]
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version = "1.9.10" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.7.3" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.6.0" }

jib-native-image-extension = { group = "com.google.cloud.tools", name = "jib-native-image-extension-gradle", version = "0.1.0" }

androidx-compose-compile = { group = "androidx.compose.compiler", name = "compiler", version.ref = "androidx-compose-compiler" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2023.06.00" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }

androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version = "2.6.1" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "2.6.1" }
androidx-lifecycle-runtime-kts = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.6.1" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.7.2" }
androidx-core-ktx = { group = "androidx.core", name = "core-kts", version = "1.10.1" }

ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version = "2.3.4" }
ktor-server-cio = { group = "io.ktor", name = "ktor-server-cio", version = "2.3.4" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version = "2.3.4" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version = "2.3.4" }

arrow-kt-suspendapp = { group = "io.arrow-kt", name = "suspendapp", version = "0.4.0" }
arrow-kt-suspendapp-ktor = { group = "io.arrow-kt", name = "suspendapp-ktor", version = "0.4.0" }

junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "5.9.2" }
junit-platform-launcher = { group = "org.junit.platform" , name = "junit-platform-launcher", version = "1.9.2" }