on: push

jobs:
  build:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Build
        run: |
          ./gradlew build

      - id: secret-check
        name: Check for Secret Availability
        run: |
          if [ "${{ secrets.GRADLE_PUBLISH_KEY }}" != '' ] && [ "${{ secrets.GRADLE_PUBLISH_SECRET }}" != '' ]; then
            echo "available=true" >> $GITHUB_OUTPUT;
          else
            echo "available=false" >> $GITHUB_OUTPUT;
          fi

      - name: Publish
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        run: |
          ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}

      - id: get-version
        name: Get Version
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        run: |
          echo "version=$(./gradlew :version -q)" >> $GITHUB_OUTPUT

      - name: Update README
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        run: |
          sed -ie "s/version \"[^\"]*\"/version \"${{ steps.get-version.outputs.version }}\"/" README.md

      - name: Commit README
        uses: test-room-7/action-update-file@v1
        with:
          file-path: README.md
          commit-msg: Update version
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Git Tag
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.outputs.version }}
          release_name: ${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
