on:
  push:
    branches:
      - 'main'
  workflow_call:
    secrets:
      ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY:
        required: true
      ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD:
        required: true
      ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME:
        required: true
      ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD:
        required: true
      GRADLE_PUBLISH_KEY:
        required: true
      GRADLE_PUBLISH_SECRET:
        required: true

concurrency: ci-${{ github.ref }}

jobs:
  check-env:
    outputs:
      credentials-defined: ${{ steps.get-credentials.outputs.defined }}
    runs-on: ubuntu-latest
    steps:
      - id: get-credentials
        env:
          ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
          ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
          ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        if: ${{ env.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY != '' && env.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD != '' && env.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME != '' && env.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD != '' && env.GRADLE_PUBLISH_KEY != '' && env.GRADLE_PUBLISH_SECRET != '' }}
        run: |
          echo "defined=true" >> $GITHUB_OUTPUT

  publish:
    needs: [ check-env ]
    if: needs.check-env.outputs.credentials-defined == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Try Publish
        env:
          ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
          ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
        run: |
          ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }} --validate-only
          ./gradlew publishToMavenCentral

      - id: get-version
        name: Get Version
        run: |
          echo "version=$(./gradlew :version -q)" >> $GITHUB_OUTPUT

      - name: Update README
        run: |
          sed -ie "s/version \"[^\"]*\"/version \"${{ steps.get-version.outputs.version }}\"/" README.md
          sed -ie "s/stables:[^\"]*\"/stables:${{ steps.get-version.outputs.version }}\"/" README.md
          sed -ie "s/version \"[^\"]*\"/version \"${{ steps.get-version.outputs.version }}\"/" example/settings.gradle.kts

      - name: Commit README
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            README.md
            example/settings.gradle.kts
          commit-msg: Update version
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Git Tag
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get-version.outputs.version }}

      - name: Complete Publish
        env:
          ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
          ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
        run: |
          ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
          ./gradlew releaseRepository
