on:
  push:
    branches:
      - '**'
concurrency: ci-${{ github.ref }}

jobs:
  build:
    name: publish
    runs-on: ubuntu-latest
    if: !contains(github.event.push.head_commit.message, 'Update version') # avoid recursion from this action updating versions in README, etc

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: |
          ./gradlew build

      - id: secret-check
        name: Check for Secret Availability
        run: |
          if [ "${{ secrets.GRADLE_PUBLISH_KEY }}" != '' ] && [ "${{ secrets.GRADLE_PUBLISH_SECRET }}" != '' ]; then
            echo "available=true" >> $GITHUB_OUTPUT;
          else
            echo "available=false" >> $GITHUB_OUTPUT;
          fi

      - name: Publish
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository


      - id: get-version
        name: Get Version
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        run: |
          echo "version=$(./gradlew :version -q)" >> $GITHUB_OUTPUT

      - name: Update README
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        run: |
          sed -ie "s/version \"[^\"]*\"/version \"${{ steps.get-version.outputs.version }}\"/" README.md
          sed -ie "s/stables:[^\"]*\"/stables:${{ steps.get-version.outputs.version }}\"/" README.md
          sed -ie "s/version \"[^\"]*\"/version \"${{ steps.get-version.outputs.version }}\"/" settings.gradle.kts
          sed -ie "s/version \"[^\"]*\"/version \"${{ steps.get-version.outputs.version }}\"/" example/settings.gradle.kts

      - name: Commit README
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            README.md
            settings.gradle.kts
            example/settings.gradle.kts
          commit-msg: Update version
          github-token: ${{ secrets.READ_WRITE_PAT }}

      - name: Create Git Tag
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get-version.outputs.version }}
