on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Update Catalogs and Test
        run: |
          ./gradlew versionCatalogUpdateStables
          ./gradlew versionCatalogUpdateUnstables
          ./gradlew test

      - name: Commit Updates
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            stables/gradle/libs.versions.toml
            unstables/gradle/libs.versions.toml
          commit-msg: Update Catalogs
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    uses: ./.github/workflows/publish.yaml